### ISSUE TITLE
Could not load site: OK (200)

### ISSUE THREAD

**Issue by aharris88** [krasnoukhov/octodmin#9]
I get this error when I run `rackup` and I got to `localhost:9292`

`Could not load site: OK (200)`

**Comment by krasnoukhov** [comment]
Hello Adam, could you post the response of `/api/site` you're getting for me? It would be much easier to understand what's going on.

**Comment by aharris88** [comment]
`{&quot;sites&quot;:{&quot;octodmin&quot;:{&quot;transliterate&quot;:&quot;latin&quot;,&quot;front_matter&quot;:{&quot;layout&quot;:{&quot;type&quot;:&quot;text&quot;},&quot;title&quot;:{&quot;type&quot;:&quot;text&quot;},&quot;slug&quot;:{&quot;type&quot;:&quot;text&quot;},&quot;date&quot;:{&quot;type&quot;:&quot;text&quot;}}},&quot;source&quot;:&quot;&#x2F;Users&#x2F;adamharris&#x2F;Development&#x2F;github&#x2F;aharris88.github.io&quot;,&quot;destination&quot;:&quot;&#x2F;Users&#x2F;adamharris&#x2F;Development&#x2F;github&#x2F;aharris88.github.io&#x2F;_site&quot;,&quot;plugins&quot;:&quot;_plugins&quot;,&quot;layouts&quot;:&quot;_layouts&quot;,&quot;data_source&quot;:&quot;_data&quot;,&quot;collections&quot;:null,&quot;safe&quot;:false,&quot;include&quot;:[&quot;.htaccess&quot;],&quot;exclude&quot;:[&quot;bower.json&quot;,&quot;README.md&quot;],&quot;keep_files&quot;:[&quot;.git&quot;,&quot;.svn&quot;],&quot;encoding&quot;:&quot;utf-8&quot;,&quot;markdown_ext&quot;:&quot;markdown,mkdown,mkdn,mkd,md&quot;,&quot;textile_ext&quot;:&quot;textile&quot;,&quot;show_drafts&quot;:null,&quot;limit_posts&quot;:0,&quot;future&quot;:true,&quot;unpublished&quot;:false,&quot;whitelist&quot;:[],&quot;gems&quot;:[],&quot;markdown&quot;:&quot;kramdown&quot;,&quot;highlighter&quot;:&quot;pygments&quot;,&quot;lsi&quot;:false,&quot;excerpt_separator&quot;:&quot;\n\n&quot;,&quot;detach&quot;:false,&quot;port&quot;:&quot;4000&quot;,&quot;host&quot;:&quot;127.0.0.1&quot;,&quot;baseurl&quot;:null,&quot;relative_permalinks&quot;:false,&quot;permalink&quot;:&quot;&#x2F;:title&#x2F;&quot;,&quot;paginate_path&quot;:&quot;&#x2F;page:num&quot;,&quot;timezone&quot;:null,&quot;quiet&quot;:false,&quot;defaults&quot;:[],&quot;maruku&quot;:{&quot;use_tex&quot;:false,&quot;use_divs&quot;:false,&quot;png_engine&quot;:&quot;blahtex&quot;,&quot;png_dir&quot;:&quot;images&#x2F;latex&quot;,&quot;png_url&quot;:&quot;&#x2F;images&#x2F;latex&quot;,&quot;fenced_code_blocks&quot;:true},&quot;rdiscount&quot;:{&quot;extensions&quot;:[]},&quot;redcarpet&quot;:{&quot;extensions&quot;:[]},&quot;kramdown&quot;:{&quot;auto_ids&quot;:true,&quot;footnote_nr&quot;:1,&quot;entity_output&quot;:&quot;as_char&quot;,&quot;toc_levels&quot;:&quot;1..6&quot;,&quot;smart_quotes&quot;:&quot;lsquo,rsquo,ldquo,rdquo&quot;,&quot;use_coderay&quot;:false,&quot;coderay&quot;:{&quot;coderay_wrap&quot;:&quot;div&quot;,&quot;coderay_line_numbers&quot;:&quot;inline&quot;,&quot;coderay_line_number_start&quot;:1,&quot;coderay_tab_width&quot;:4,&quot;coderay_bold_every&quot;:10,&quot;coderay_css&quot;:&quot;style&quot;}},&quot;redcloth&quot;:{&quot;hard_breaks&quot;:true},&quot;title&quot;:&quot;Adam Harris&quot;,&quot;description&quot;:&quot;Web Developer&quot;,&quot;category_dir&quot;:&quot;category&quot;,&quot;paginate&quot;:5,&quot;siteurl&quot;:&quot;http:&#x2F;&#x2F;www.adamwadeharris.com&quot;,&quot;disqus_shortname&quot;:&quot;adamwadeharris&quot;,&quot;google_analytics_code&quot;:&quot;UA-31980509-3&quot;,&quot;google_analytics_url&quot;:&quot;adamwadeharris.com&quot;,&quot;prose&quot;:{&quot;media&quot;:&quot;assets&#x2F;uploads&quot;,&quot;siteurl&quot;:&quot;http:&#x2F;&#x2F;www.adamwadeharris.com&quot;},&quot;post_ext&quot;:&quot;markdown&quot;,&quot;post_layout&quot;:&quot;post&quot;}}`

**Comment by krasnoukhov** [comment]
Well, that doesn't look like a parseable JSON. What Ruby version you're running?

**Comment by aharris88** [comment]
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

**Comment by krasnoukhov** [comment]
Strange, should be working fine. Could you `curl http://localhost:9292/api/site` and paste the exact output?

**Comment by aharris88** [comment]
It's the exact same thing.
![screen shot 2015-03-27 at 1 11 07 pm](https://cloud.githubusercontent.com/assets/3266363/6875230/cbb28078-d482-11e4-8e83-fdf1f60e7abd.png)

**Comment by krasnoukhov** [comment]
Super strange! I'll check this and get back to you.

**Comment by krasnoukhov** [comment]
Yeah okay, it's due to a lotus update, give me a couple of minutes and I'll release a fix

**Comment by krasnoukhov** [comment]
Fixed in https://github.com/krasnoukhov/octodmin/commit/da6c2177d48ccddc45abd795a7fc9b2de37c9f64
Also, 0.3.4 is pushed. Enjoy!

**Comment by aharris88** [comment]
That's working a lot better! Thanks!

It's not finding my posts though, it just sits there and  spins. I put in a new issue #10.
